---
steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '--tag=gcr.io/${PROJECT_ID}/docker:latest'
  - '--file=Dockerfile-cloudbuild'
  - '.'
  waitFor:
    - "-"
  id: builder
- name: 'gcr.io/${PROJECT_ID}/docker'
  args:
    - 'build'
    - '--tag=gcr.io/${PROJECT_ID}/ctl-archlinux:latest'
    - '--file=./mirror-monitor/docker/archlinux/20200106/Dockerfile'
    - './mirror-monitor/docker/archlinux/20200106'
  waitFor:
    - builder
- name: 'gcr.io/${PROJECT_ID}/docker'
  args:
    - 'build'
    - '--tag=gcr.io/${PROJECT_ID}/ctl-centos6:latest'
    - '--file=./mirror-monitor/docker/centos/6/Dockerfile'
    - './mirror-monitor/docker/centos/6'
  waitFor:
    - builder
- name: 'gcr.io/${PROJECT_ID}/docker'
  args:
    - 'build'
    - '--tag=gcr.io/${PROJECT_ID}/ctl-centos7:latest'
    - '--file=./mirror-monitor/docker/centos/7/Dockerfile'
    - './mirror-monitor/docker/centos/7'
  waitFor:
    - builder
- name: 'gcr.io/${PROJECT_ID}/docker'
  args:
    - 'build'
    - '--tag=gcr.io/${PROJECT_ID}/ctl-centos8:latest'
    - '--file=./mirror-monitor/docker/centos/8/Dockerfile'
    - './mirror-monitor/docker/centos/8'
  waitFor:
    - builder
- name: 'gcr.io/${PROJECT_ID}/docker'
  args:
    - 'build'
    - '--tag=gcr.io/${PROJECT_ID}/ctl-debian8:latest'
    - '--file=./mirror-monitor/docker/debian/8/Dockerfile'
    - './mirror-monitor/docker/debian/8'
  waitFor:
    - builder
- name: 'gcr.io/${PROJECT_ID}/docker'
  args:
    - 'build'
    - '--tag=gcr.io/${PROJECT_ID}/ctl-debian9:latest'
    - '--file=./mirror-monitor/docker/debian/9/Dockerfile'
    - './mirror-monitor/docker/debian/9'
  waitFor:
    - builder
- name: 'gcr.io/${PROJECT_ID}/docker'
  args:
    - 'build'
    - '--tag=gcr.io/${PROJECT_ID}/ctl-ubuntu1604:latest'
    - '--file=./mirror-monitor/docker/ubuntu/1604/Dockerfile'
    - './mirror-monitor/docker/ubuntu/1604'
  waitFor:
    - builder
- name: 'gcr.io/${PROJECT_ID}/docker'
  args:
    - 'build'
    - '--tag=gcr.io/${PROJECT_ID}/ctl-ubuntu1804:latest'
    - '--file=./mirror-monitor/docker/ubuntu/1804/Dockerfile'
    - './mirror-monitor/docker/ubuntu/1804'
  waitFor:
    - builder
- name: 'gcr.io/${PROJECT_ID}/docker'
  args:
    - 'build'
    - '--tag=gcr.io/${PROJECT_ID}/ctl-fedora26:latest'
    - '--file=./mirror-monitor/docker/fedora/26/Dockerfile'
    - './mirror-monitor/docker/fedora/26'
  waitFor:
    - builder
- name: 'gcr.io/${PROJECT_ID}/docker'
  args:
    - 'build'
    - '--tag=gcr.io/${PROJECT_ID}/ctl-fedora27:latest'
    - '--file=./mirror-monitor/docker/fedora/27/Dockerfile'
    - './mirror-monitor/docker/fedora/27'
  waitFor:
    - builder
- name: 'gcr.io/${PROJECT_ID}/docker'
  args:
    - 'build'
    - '--tag=gcr.io/${PROJECT_ID}/ctl-fedora28:latest'
    - '--file=./mirror-monitor/docker/fedora/28/Dockerfile'
    - './mirror-monitor/docker/fedora/28'
  waitFor:
    - builder
- name: 'gcr.io/${PROJECT_ID}/docker'
  args:
    - 'build'
    - '--tag=gcr.io/${PROJECT_ID}/ctl-fedora29:latest'
    - '--file=./mirror-monitor/docker/fedora/29/Dockerfile'
    - './mirror-monitor/docker/fedora/29'
  waitFor:
    - builder
- name: 'gcr.io/${PROJECT_ID}/docker'
  args:
    - 'build'
    - '--tag=gcr.io/${PROJECT_ID}/ctl-fedora30:latest'
    - '--file=./mirror-monitor/docker/fedora/30/Dockerfile'
    - './mirror-monitor/docker/fedora/30'
  waitFor:
    - builder
- name: 'gcr.io/${PROJECT_ID}/docker'
  args:
    - 'build'
    - '--tag=gcr.io/${PROJECT_ID}/ctl-fedora31:latest'
    - '--file=./mirror-monitor/docker/fedora/31/Dockerfile'
    - './mirror-monitor/docker/fedora/31'
  waitFor:
    - builder
images:
- 'gcr.io/${PROJECT_ID}/docker:latest'
- 'gcr.io/${PROJECT_ID}/ctl-archlinux:latest'
- 'gcr.io/${PROJECT_ID}/ctl-centos6:latest'
- 'gcr.io/${PROJECT_ID}/ctl-centos7:latest'
- 'gcr.io/${PROJECT_ID}/ctl-centos8:latest'
- 'gcr.io/${PROJECT_ID}/ctl-debian8:latest'
- 'gcr.io/${PROJECT_ID}/ctl-debian9:latest'
- 'gcr.io/${PROJECT_ID}/ctl-ubuntu1604:latest'
- 'gcr.io/${PROJECT_ID}/ctl-ubuntu1804:latest'
- 'gcr.io/${PROJECT_ID}/ctl-fedora26:latest'
- 'gcr.io/${PROJECT_ID}/ctl-fedora27:latest'
- 'gcr.io/${PROJECT_ID}/ctl-fedora28:latest'
- 'gcr.io/${PROJECT_ID}/ctl-fedora29:latest'
- 'gcr.io/${PROJECT_ID}/ctl-fedora30:latest'
- 'gcr.io/${PROJECT_ID}/ctl-fedora31:latest'
timeout: 1800s
options:
  machineType: N1_HIGHCPU_32