---
steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '--tag=gcr.io/${PROJECT_ID}/docker:latest'
  - '--file=Dockerfile-cloudbuild'
  - '.'
- name: 'gcr.io/${PROJECT_ID}/docker'
  args:
    - 'build'
    - '--tag=gcr.io/${PROJECT_ID}/ctl-archlinux:latest'
    - '--file=archlinux/20200106/Dockerfile'
    - '.'
- name: 'gcr.io/${PROJECT_ID}/docker'
  args:
    - 'build'
    - '--tag=gcr.io/${PROJECT_ID}/ctl-centos6:latest'
    - '--file=centos/6/Dockerfile'
    - '.'
- name: 'gcr.io/${PROJECT_ID}/docker'
  args:
    - 'build'
    - '--tag=gcr.io/${PROJECT_ID}/ctl-centos7:latest'
    - '--file=centos/7/Dockerfile'
    - '.'
- name: 'gcr.io/${PROJECT_ID}/docker'
  args:
    - 'build'
    - '--tag=gcr.io/${PROJECT_ID}/ctl-centos8:latest'
    - '--file=centos/8/Dockerfile'
    - '.'
- name: 'gcr.io/${PROJECT_ID}/docker'
  args:
    - 'build'
    - '--tag=gcr.io/${PROJECT_ID}/ctl-debian8:latest'
    - '--file=debian/8/Dockerfile'
    - '.'
- name: 'gcr.io/${PROJECT_ID}/docker'
  args:
    - 'build'
    - '--tag=gcr.io/${PROJECT_ID}/ctl-debian9:latest'
    - '--file=debian/8/Dockerfile'
    - '.'
- name: 'gcr.io/${PROJECT_ID}/docker'
  args:
    - 'build'
    - '--tag=gcr.io/${PROJECT_ID}/ctl-ubuntu1604:latest'
    - '--file=ubuntu/1604/Dockerfile'
    - '.'
- name: 'gcr.io/${PROJECT_ID}/docker'
  args:
    - 'build'
    - '--tag=gcr.io/${PROJECT_ID}/ctl-ubuntu1804:latest'
    - '--file=ubuntu/1804/Dockerfile'
    - '.'
- name: 'gcr.io/${PROJECT_ID}/docker'
  args:
    - 'build'
    - '--tag=gcr.io/${PROJECT_ID}/ctl-fedora26:latest'
    - '--file=fedora/26/Dockerfile'
    - '.'
- name: 'gcr.io/${PROJECT_ID}/docker'
  args:
    - 'build'
    - '--tag=gcr.io/${PROJECT_ID}/ctl-fedora27:latest'
    - '--file=fedora/27/Dockerfile'
    - '.'
- name: 'gcr.io/${PROJECT_ID}/docker'
  args:
    - 'build'
    - '--tag=gcr.io/${PROJECT_ID}/ctl-fedora28:latest'
    - '--file=fedora/28/Dockerfile'
    - '.'
- name: 'gcr.io/${PROJECT_ID}/docker'
  args:
    - 'build'
    - '--tag=gcr.io/${PROJECT_ID}/ctl-fedora29:latest'
    - '--file=fedora/29/Dockerfile'
    - '.'
- name: 'gcr.io/${PROJECT_ID}/docker'
  args:
    - 'build'
    - '--tag=gcr.io/${PROJECT_ID}/ctl-fedora30:latest'
    - '--file=fedora/30/Dockerfile'
    - '.'
- name: 'gcr.io/${PROJECT_ID}/docker'
  args:
    - 'build'
    - '--tag=gcr.io/${PROJECT_ID}/ctl-fedora31:latest'
    - '--file=fedora/31/Dockerfile'
    - '.'
images:
- 'gcr.io/${PROJECT_ID}/docker:latest'
- 'gcr.io/${PROJECT_ID}/ctl-archlinux:latest'
- 'gcr.io/${PROJECT_ID}/ctl-centos6:latest'
- 'gcr.io/${PROJECT_ID}/ctl-centos7:latest'
- 'gcr.io/${PROJECT_ID}/ctl-centos8:latest'
- 'gcr.io/${PROJECT_ID}/ctl-debian8:latest'
- 'gcr.io/${PROJECT_ID}/ctl-debian9:latest'
- 'gcr.io/${PROJECT_ID}/ctl-ubuntu1604:latest'
- 'gcr.io/${PROJECT_ID}/ctl-ubuntu1804:latest'
- 'gcr.io/${PROJECT_ID}/ctl-fedora26:latest'
- 'gcr.io/${PROJECT_ID}/ctl-fedora27:latest'
- 'gcr.io/${PROJECT_ID}/ctl-fedora28:latest'
- 'gcr.io/${PROJECT_ID}/ctl-fedora29:latest'
- 'gcr.io/${PROJECT_ID}/ctl-fedora30:latest'
- 'gcr.io/${PROJECT_ID}/ctl-fedora31:latest'